## This configuration was generated by terraform-provider-oci

resource oci_core_cpe export_CPE-VpnExample {
  compartment_id      = var.compartment_ocid
  cpe_device_shape_id = "0c14a129-ce70-43f3-bf07-e980a6784ae8"
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2021-05-19T12:47:40.244Z"
  }
  display_name = "CPE-VpnExample"
  freeform_tags = {
    "IPSec_VPN_Connection" = "IPSec_VPN_Connection-2021-05-19T12:19:58"
  }
  ip_address = "<replace-with-your-public-ip>"
}

resource oci_core_cpe export_udm {
  compartment_id      = var.compartment_ocid
  cpe_device_shape_id = "0c14a129-ce70-43f3-bf07-e980a6784ae8"
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-11T19:52:52.706Z"
  }
  display_name = "udm"
  freeform_tags = {
    "vpn-solution" = "2022-09-11T20:03:39.715Z"
  }
  ip_address = "75.97.192.54"
}

resource oci_core_drg_attachment export_drgattachment20220911203527 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-11T20:35:27.453Z"
  }
  display_name       = "drgattachment20220911203527"
  drg_id             = oci_core_drg.export_drg1.id
  drg_route_table_id = oci_core_drg_route_table.export_Autogenerated-Drg-Route-Table-for-VCN-attachments.id
  #export_drg_route_distribution_id = <<Optional value not found in discovery>>
  freeform_tags = {
    "vpn-solution" = "2022-09-11T20:03:39.715Z"
  }
  network_details {
    id = oci_core_vcn.export_vcn1.id
    #route_table_id = <<Optional value not found in discovery>>
    type           = "VCN"
    vcn_route_type = "SUBNET_CIDRS"
  }
  #remove_export_drg_route_distribution_trigger = <<Optional value not found in discovery>>
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn1.id
}

resource oci_core_drg export_drg1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-11T20:35:16.770Z"
  }
  display_name = "drg1"
  freeform_tags = {
    "vpn-solution" = "2022-09-11T20:03:39.715Z"
  }
}

resource oci_core_drg export_DRG-VpnExample {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2021-05-19T12:47:40.228Z"
  }
  display_name = "DRG-VpnExample"
  freeform_tags = {
    "IPSec_VPN_Connection" = "IPSec_VPN_Connection-2021-05-19T12:19:58"
  }
}

resource oci_core_drg_route_distribution export_Default-Export-Route-Distribution-for-DRG-drg1 {
  defined_tags = {
  }
  display_name      = "Default Export Route Distribution for DRG: drg1"
  distribution_type = "EXPORT"
  drg_id            = oci_core_drg.export_drg1.id
  freeform_tags = {
  }
}

resource oci_core_drg_route_distribution export_Autogenerated-Import-Route-Distribution-for-ALL-routes {
  defined_tags = {
  }
  display_name      = "Autogenerated Import Route Distribution for ALL routes"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_drg1.id
  freeform_tags = {
  }
}

resource oci_core_drg_route_distribution export_Autogenerated-Import-Route-Distribution-for-VCN-Routes {
  defined_tags = {
  }
  display_name      = "Autogenerated Import Route Distribution for VCN Routes"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_drg1.id
  freeform_tags = {
  }
}

resource oci_core_drg_route_table export_Autogenerated-Drg-Route-Table-for-VCN-attachments {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-11T20:35:16.770Z"
  }
  display_name = "Autogenerated Drg Route Table for VCN attachments"
  drg_id       = oci_core_drg.export_drg1.id
  freeform_tags = {
    "vpn-solution" = "2022-09-11T20:03:39.715Z"
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_Autogenerated-Import-Route-Distribution-for-ALL-routes.id
  is_ecmp_enabled                  = "false"
  #remove_import_trigger = <<Optional value not found in discovery>>
}

resource oci_core_drg_route_table export_Autogenerated-Drg-Route-Table-for-RPC-VC-and-IPSec-attachments {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-11T20:35:16.770Z"
  }
  display_name = "Autogenerated Drg Route Table for RPC, VC, and IPSec attachments"
  drg_id       = oci_core_drg.export_drg1.id
  freeform_tags = {
    "vpn-solution" = "2022-09-11T20:03:39.715Z"
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_Autogenerated-Import-Route-Distribution-for-VCN-Routes.id
  is_ecmp_enabled                  = "false"
  #remove_import_trigger = <<Optional value not found in discovery>>
}

resource oci_core_drg_route_table_route_rule export_Autogenerated-Drg-Route-Table-for-VCN-attachments_drg_route_table_route_rule_1 {
  destination                = "10.0.0.0/24"
  destination_type           = "CIDR_BLOCK"
  drg_route_table_id         = oci_core_drg_route_table.export_Autogenerated-Drg-Route-Table-for-VCN-attachments.id
  next_hop_drg_attachment_id = oci_core_drg_attachment.export_drgattachment20220911203527.id
}

resource oci_core_drg_route_table_route_rule export_Autogenerated-Drg-Route-Table-for-VCN-attachments_drg_route_table_route_rule_2 {
  destination                = "192.168.0.0/24"
  destination_type           = "CIDR_BLOCK"
  drg_route_table_id         = oci_core_drg_route_table.export_Autogenerated-Drg-Route-Table-for-VCN-attachments.id
  next_hop_drg_attachment_id = "ocid1.drgattachment.oc1.iad.aaaaaaaavx25uguyn6o3ofntmg3ostolvogv3dur7y2igsbj5ra74ys54rra"
}

resource oci_core_drg_route_table_route_rule export_Autogenerated-Drg-Route-Table-for-VCN-attachments_drg_route_table_route_rule_3 {
  destination                = "192.168.0.0/24"
  destination_type           = "CIDR_BLOCK"
  drg_route_table_id         = oci_core_drg_route_table.export_Autogenerated-Drg-Route-Table-for-VCN-attachments.id
  next_hop_drg_attachment_id = "ocid1.drgattachment.oc1.iad.aaaaaaaa66xov3nrq2veqqor5jnzxrmdoabfbpdqm5y2hppsmrtit6lpcjxq"
}

resource oci_core_drg_route_table_route_rule export_Autogenerated-Drg-Route-Table-for-RPC-VC-and-IPSec-attachments_drg_route_table_route_rule_1 {
  destination                = "10.0.0.0/24"
  destination_type           = "CIDR_BLOCK"
  drg_route_table_id         = oci_core_drg_route_table.export_Autogenerated-Drg-Route-Table-for-RPC-VC-and-IPSec-attachments.id
  next_hop_drg_attachment_id = oci_core_drg_attachment.export_drgattachment20220911203527.id
}

resource oci_core_drg_route_distribution export_Default-Export-Route-Distribution-for-DRG-DRG-VpnExample {
  defined_tags = {
  }
  display_name      = "Default Export Route Distribution for DRG: DRG-VpnExample"
  distribution_type = "EXPORT"
  drg_id            = oci_core_drg.export_DRG-VpnExample.id
  freeform_tags = {
  }
}

resource oci_core_drg_route_distribution export_Autogenerated-Import-Route-Distribution-for-ALL-routes_1 {
  defined_tags = {
  }
  display_name      = "Autogenerated Import Route Distribution for ALL routes"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_DRG-VpnExample.id
  freeform_tags = {
  }
}

resource oci_core_drg_route_distribution export_Autogenerated-Import-Route-Distribution-for-VCN-Routes_1 {
  defined_tags = {
  }
  display_name      = "Autogenerated Import Route Distribution for VCN Routes"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_DRG-VpnExample.id
  freeform_tags = {
  }
}

resource oci_core_drg_route_table export_Autogenerated-Drg-Route-Table-for-VCN-attachments_1 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2021-05-19T12:47:40.228Z"
  }
  display_name = "Autogenerated Drg Route Table for VCN attachments"
  drg_id       = oci_core_drg.export_DRG-VpnExample.id
  freeform_tags = {
    "IPSec_VPN_Connection" = "IPSec_VPN_Connection-2021-05-19T12:19:58"
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_Autogenerated-Import-Route-Distribution-for-ALL-routes_1.id
  is_ecmp_enabled                  = "false"
  #remove_import_trigger = <<Optional value not found in discovery>>
}

resource oci_core_drg_route_table export_Autogenerated-Drg-Route-Table-for-RPC-VC-and-IPSec-attachments_1 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2021-05-19T12:47:40.228Z"
  }
  display_name = "Autogenerated Drg Route Table for RPC, VC, and IPSec attachments"
  drg_id       = oci_core_drg.export_DRG-VpnExample.id
  freeform_tags = {
    "IPSec_VPN_Connection" = "IPSec_VPN_Connection-2021-05-19T12:19:58"
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_Autogenerated-Import-Route-Distribution-for-VCN-Routes_1.id
  is_ecmp_enabled                  = "false"
  #remove_import_trigger = <<Optional value not found in discovery>>
}

resource oci_core_internet_gateway export_internet-gateway1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-11T20:35:16.834Z"
  }
  display_name = "internet-gateway1"
  enabled      = "true"
  freeform_tags = {
    "vpn-solution" = "2022-09-11T20:03:39.715Z"
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn1.id
}

resource oci_core_ipsec export_vpn1-vcn1 {
  compartment_id            = var.compartment_ocid
  cpe_id                    = oci_core_cpe.export_udm.id
  cpe_local_identifier      = "<replace-with-your-own-public-IP>"
  cpe_local_identifier_type = "IP_ADDRESS"
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-11T20:35:26.870Z"
  }
  display_name = "vpn1-vcn1"
  drg_id       = oci_core_drg.export_drg1.id
  freeform_tags = {
    "vpn-solution" = "2022-09-11T20:03:39.715Z"
  }
  static_routes = [
    "192.168.0.0/24",
  ]
}

resource oci_core_subnet export_subnet1 {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-11T20:03:15.353Z"
  }
  dhcp_options_id = oci_core_vcn.export_vcn1.default_dhcp_options_id
  display_name    = "subnet1"
  dns_label       = "subnet1"
  freeform_tags = {
    "vpn-solution" = "2022-09-11T20:03:39.715Z"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_vcn.export_vcn1.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_vcn1.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_vcn1.id
}

resource oci_core_private_ip export_instance-20220917-1932 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-17T23:35:00.548Z"
  }
  display_name = "instance-20220917-1932"
  freeform_tags = {
  }
  hostname_label = "instance-20220917-1932"
  ip_address     = "10.0.0.49"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljthunfypognkjaxxe4wcrpui42ht2edxpw7embf36az3nr62jo2ena"
}

resource oci_core_private_ip export_instance-20220917-1813 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-17T22:22:48.772Z"
  }
  display_name = "instance-20220917-1813"
  freeform_tags = {
  }
  hostname_label = "instance-20220917-1813"
  ip_address     = "10.0.0.106"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljtl66rpbnfbk3xeufiy7g6nrcdbw73t6ng7f4mjx3pfa5thlsygx5q"
}

resource oci_core_vcn export_vcn1 {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-11T19:59:56.474Z"
  }
  display_name = "vcn1"
  dns_label    = "vcn1"
  freeform_tags = {
    "vpn-solution" = "2022-09-11T20:03:39.715Z"
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-vcn1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-11T19:59:56.474Z"
  }
  display_name     = "Default DHCP Options for vcn1"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_vcn1.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "vcn1.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_default_route_table export_Default-Route-Table-for-vcn1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-11T19:59:56.474Z"
  }
  display_name = "Default Route Table for vcn1"
  freeform_tags = {
    "vpn-solution" = "2022-09-11T20:03:39.715Z"
  }
  manage_default_resource_id = oci_core_vcn.export_vcn1.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "192.168.0.0/24"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_drg.export_drg1.id
    #route_type = <<Optional value not found in discovery>>
  }
}

resource oci_core_default_security_list export_Default-Security-List-for-vcn1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2022-09-11T19:59:56.474Z"
  }
  display_name = "Default Security List for vcn1"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "192.168.0.0/24"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "vpn-solution" = "2022-09-11T20:03:39.715Z"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "all"
    source      = "192.168.0.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_vcn1.default_security_list_id
}

