## This configuration was generated by terraform-provider-oci

resource oci_logging_log_group export_Default_Group {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2021-05-25T02:42:27.146Z"
  }
  description  = "The log group auto created for the users in selected comparmtent"
  display_name = "Default_Group"
  freeform_tags = {
  }
}

resource oci_logging_log export_subnet_20210522_1407_all {
  configuration {
    compartment_id = var.compartment_ocid
    source {
      category    = "all"
      resource    = "ocid1.subnet.oc1.iad.aaaaaaaazcpiyqvtxkptehlhbhkcp7mrig3wkdhlkivyoz7ihj27h4b3wsbq"
      service     = "flowlogs"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2021-05-25T02:44:32.224Z"
  }
  display_name = "subnet_20210522_1407_all"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_Default_Group.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

resource oci_logging_log export_lb_2021_0524_2132_error {
  configuration {
    compartment_id = var.compartment_ocid
    source {
      category    = "error"
      resource    = "ocid1.loadbalancer.oc1.iad.aaaaaaaak5bmc4kxhoa4sn5oszjorfqeqwctmyxfaidne5qpvqunbuhviztq"
      service     = "loadbalancer"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2021-05-25T02:42:42.113Z"
  }
  display_name = "lb_2021_0524_2132_error"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_Default_Group.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

resource oci_logging_log export_lb_2021_0524_2132_access {
  configuration {
    compartment_id = var.compartment_ocid
    source {
      category    = "access"
      resource    = "ocid1.loadbalancer.oc1.iad.aaaaaaaak5bmc4kxhoa4sn5oszjorfqeqwctmyxfaidne5qpvqunbuhviztq"
      service     = "loadbalancer"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2021-05-25T02:42:28.099Z"
  }
  display_name = "lb_2021_0524_2132_access"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_Default_Group.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

