## This configuration was generated by terraform-provider-oci

resource oci_monitoring_alarm export_Tunnel-State-Alarm-2-VpnExample {
  #body = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2021-05-19T12:47:52.605Z"
  }
  destinations = [
    oci_ons_notification_topic.export_IpSecTunnel.id,
  ]
  display_name = "Tunnel-State-Alarm-2-VpnExample"
  freeform_tags = {
    "IPSec_VPN_Connection" = "IPSec_VPN_Connection-2021-05-19T12:19:58"
  }
  is_enabled                                    = "true"
  is_notifications_per_metric_dimension_enabled = "false"
  message_format                                = "RAW"
  metric_compartment_id                         = var.compartment_ocid
  metric_compartment_id_in_subtree              = "false"
  namespace                                     = "oci_vpn"
  pending_duration                              = "PT1M"
  query                                         = "vpn_tunnel_state[1m]{resourceId = \"ocid1.ipsectunnel.oc1.iad.aaaaaaaarywn2p3lmxy2kifrhvy5ffsc5q5ufvu4wf4tz4ltezosxudpxqpa\"}.mean() < 1"
  #repeat_notification_duration = <<Optional value not found in discovery>>
  resolution = "1m"
  #resource_group = <<Optional value not found in discovery>>
  severity = "INFO"
}

resource oci_monitoring_alarm export_Tunnel-State-Alarm-1-VpnExample {
  #body = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2021-05-19T12:47:52.304Z"
  }
  destinations = [
    oci_ons_notification_topic.export_IpSecTunnel.id,
  ]
  display_name = "Tunnel-State-Alarm-1-VpnExample"
  freeform_tags = {
    "IPSec_VPN_Connection" = "IPSec_VPN_Connection-2021-05-19T12:19:58"
  }
  is_enabled                                    = "true"
  is_notifications_per_metric_dimension_enabled = "false"
  message_format                                = "RAW"
  metric_compartment_id                         = var.compartment_ocid
  metric_compartment_id_in_subtree              = "false"
  namespace                                     = "oci_vpn"
  pending_duration                              = "PT1M"
  query                                         = "vpn_tunnel_state[1m]{resourceId = \"ocid1.ipsectunnel.oc1.iad.aaaaaaaaq2me72soqv2qekhskwdey6ztfqqhzeo2nhquvozq5773wfd5qgyq\"}.mean() < 1"
  #repeat_notification_duration = <<Optional value not found in discovery>>
  resolution = "1m"
  #resource_group = <<Optional value not found in discovery>>
  severity = "INFO"
}

