## This configuration was generated by terraform-provider-oci

resource oci_ons_notification_topic export_IpSecTunnel {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2021-05-19T12:47:40.089Z"
  }
  #description = <<Optional value not found in discovery>>
  freeform_tags = {
    "IPSec_VPN_Connection" = "IPSec_VPN_Connection-2021-05-19T12:19:58"
  }
  name = "IpSecTunnel"
}

resource oci_ons_subscription export_subscription_1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azuread/example@example.com"
    "Oracle-Tags.CreatedOn" = "2021-05-19T12:47:40.898Z"
  }
  delivery_policy = "{\"backoffRetryPolicy\":{\"maxRetryDuration\":7200000,\"policyType\":\"EXPONENTIAL\"}}"
  endpoint        = "example@example.com"
  freeform_tags = {
    "IPSec_VPN_Connection" = "IPSec_VPN_Connection-2021-05-19T12:19:58"
  }
  protocol = "EMAIL"
  topic_id = oci_ons_notification_topic.export_IpSecTunnel.id
}

